# Generated by Django 5.1.5 on 2025-01-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=30, unique=True)),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('cliente_cif', models.CharField(max_length=12, verbose_name='CIF')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('direccion_envio', models.TextField(verbose_name='Dirección de Envío')),
                ('documento', models.FileField(blank=True, null=True, upload_to='pedidos/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('referencia', models.CharField(max_length=20, verbose_name='Referencia')),
                ('cantidad', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
        ),
    ]
