# Generated by Django 5.1.5 on 2025-01-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Pedido')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Número de Pedido')),
                ('order_date', models.DateField(verbose_name='Fecha del Pedido')),
                ('client_name', models.CharField(max_length=30, verbose_name='Nombre del Cliente')),
                ('cif', models.CharField(max_length=15, verbose_name='CIF')),
                ('shipping_address', models.CharField(max_length=50, verbose_name='Dirección de Envío')),
                ('file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ruta del Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Order_info',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id_status_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Estado')),
                ('status_name', models.CharField(max_length=20, unique=True, verbose_name='Estado')),
            ],
            options={
                'db_table': 'Status_type',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Referencia')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('description', models.CharField(max_length=100, verbose_name='Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pedidos.orderinfo', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
                'db_table': 'Order_data',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.statustype', verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
