# Generated by Django 5.1.5 on 2025-02-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_orderinfo_statustype_orderdata_orderinfo_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ['status_name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='id_order',
            field=models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pedidos.orderinfo', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.statustype', verbose_name='Estado'),
        ),
    ]
